import type { Metadata } from "next";

/**
 * Per-route share metadata.
 *
 * Next merges metadata from segments *shallowly*: a page that defines
 * `openGraph` at all replaces the layout's `openGraph` wholesale, losing
 * `siteName`, `type` and `images` with it. So every page builds its object
 * through this helper rather than by hand, and the pieces that must not vary
 * are set in one place.
 *
 * Before this, every route inherited the root layout's card: seven pages that
 * shared one title, one description and one `og:url` pointing at `/`. A link
 * to the PeerTube comparison previewed as the homepage. On a project that
 * travels by pasted link, the card is the first pixel of the brand.
 */

/**
 * The default share card. It carries the install command *as well as* the
 * positioning line: a card that says only "Run your own video platform" is a
 * card any of a dozen self-hosting projects could post, and the command is the
 * one thing on it that is checkably ours.
 *
 * Regenerate with `node scripts/og-card.mjs`, which reads the command out of
 * this directory's `site.ts` so the card cannot drift from the fact table.
 * `og-card.png` beside it is the canon's own card, still generated by
 * vidra-branding, and is deliberately left alone.
 */
export const OG_CARD = {
  url: "/brand/og-card-install.png",
  width: 1200,
  height: 630,
  alt: "Vidra — run your own video platform — above the one-line install command, curl piped to sh",
} as const;

/**
 * Cards for the two pages that actually get pasted into threads, each
 * carrying that page's own evidence rather than the install command. A page
 * card is only worth making when it says something its neighbours do not.
 */
export const OG_CARD_PEERTUBE = {
  ...OG_CARD,
  url: "/brand/og-card-peertube.png",
  alt: "Vidra — run your own video platform — above the line: PeerTube 8.2.4, every cell checked 2026-08-30",
} as const;

export const OG_CARD_IPFS = {
  ...OG_CARD,
  url: "/brand/og-card-ipfs.png",
  alt: "Vidra — run your own video platform — above the line: every public video's CIDs are in the API, pin one yourself",
} as const;

type PageMeta = {
  /** The `<title>`, which the root layout's template suffixes with "— Vidra". */
  title: string;
  /**
   * A title that ignores the template, for the one page whose own title
   * already names both products and would otherwise read "Vidra vs PeerTube —
   * Vidra".
   */
  absoluteTitle?: string;
  description: string;
  /** This route, so `og:url` points at the page that was actually shared. */
  path: string;
  /** Overrides the install-command card with one carrying this page's own evidence. */
  card?: { url: string; width: number; height: number; alt: string };
};

export function pageMetadata({
  title,
  absoluteTitle,
  description,
  path,
  card = OG_CARD,
}: PageMeta): Metadata {
  const shareTitle = absoluteTitle ?? `${title} — Vidra`;

  return {
    title: absoluteTitle ? { absolute: absoluteTitle } : title,
    description,
    openGraph: {
      type: "website",
      siteName: "Vidra",
      title: shareTitle,
      description,
      url: path,
      images: [card],
    },
    twitter: {
      card: "summary_large_image",
      title: shareTitle,
      description,
      images: [card.url],
    },
  };
}
