import { OG_CARD_PEERTUBE, pageMetadata } from "@/lib/metadata";
import { Button, TextLink } from "@/components/Button";
import { Comparison, type ComparisonRow } from "@/components/Comparison";
import { Eyebrow, Head, Section, Standfirst } from "@/components/Section";
import { DOCS, INSTALL_ANCHOR, MESSAGING, SCALE, VERSION } from "@/lib/site";

export const metadata = pageMetadata({
  title: "Vidra vs PeerTube",
  // The layout's "%s — Vidra" template rendered this as "Vidra vs PeerTube —
  // Vidra", which reads as a typo in every search result and every tab.
  absoluteTitle: "Vidra vs PeerTube — self-hosted video, compared",
  path: "/compare/peertube",
  card: OG_CARD_PEERTUBE,
  description:
    "Vidra and PeerTube, compared honestly: federation, Bluesky sign-in, direct messages, uploads, operability, scaling, in-player P2P — checked against PeerTube 8.2.4, August 2026 — where PeerTube wins, when to pick it, and the one-way migration path.",
});

/**
 * The PeerTube column is checked against PeerTube's own documentation,
 * repository and package index, version-pinned and date-stamped in the visible
 * caption below the table, so the claims age honestly. The Vidra column traces
 * to the Vidra repositories, per hard rule 5.
 *
 * Two rules this page has learned the hard way.
 *
 * First: a forfeited cell is not neutrality. "Judge it from PeerTube's own
 * documentation" appeared twice, in the two rows where Vidra's answer is
 * longest, and a blank next to a paragraph reads as an absence rather than as
 * restraint. Both are filled now, by quoting PeerTube's documented path
 * plainly.
 *
 * Second: the rows where PeerTube wins have to be in the table, not implied by
 * their absence. A comparison with no losing rows is an advertisement, and a
 * PeerTube admin reading it stops believing the rest.
 *
 * Re-check trigger: 8.3.0-rc.1 shipped 2026-08-25. When 8.3.0 goes stable this
 * page needs a pass — the mass-blocklist work alone changes the federation
 * paragraph on the homepage.
 */
const COLUMNS = ["PeerTube", "Vidra"];

const ROWS: ComparisonRow[] = [
  {
    label: "Lineage",
    cells: [
      "The established ActivityPub video platform; current stable v8.2.4 (August 2026).",
      `A clean-room implementation, ${VERSION} — not a fork, and not PeerTube-API-compatible.`,
    ],
  },
  {
    label: "Federation",
    cells: [
      // 8.2.0 shipped 2026-05-27; 8.2.4 shipped 2026-08-04. "8.2, August 2026"
      // paired a minor with the wrong month, which is exactly the kind of
      // detail the reader who checks it will check.
      "ActivityPub (as of 8.2.4, August 2026).",
      "ActivityPub federation, enabled per instance; once on, every channel federates by default and can opt out.",
    ],
  },
  {
    label: "Bluesky",
    cells: [
      "No ATProto support as of v8.2.4.",
      "Viewers sign in with Bluesky or any ATProto PDS; opt-in cross-posting of public videos. Outbound only — no inbound path.",
    ],
  },
  {
    label: "Direct messages",
    cells: [
      "None as of v8.2.4 (August 2026) — the closest surface is the moderation thread on an abuse report.",
      `One-to-one messages, with an opt-in end-to-end encrypted mode — Olm in the browser, so the server stores only ciphertext; not independently audited — and disappearing timers, ${MESSAGING.timerMin} to ${MESSAGING.timerMax}, on encrypted conversations.`,
    ],
  },
  {
    label: "In-player P2P",
    cells: [
      "Built in: playback shares bandwidth between viewers over WebRTC, and a viewer can turn it off.",
      `None in ${VERSION}. On the roadmap — do not size your bandwidth around it.`,
    ],
  },
  {
    // PeerTube cell checked against docs.joinpeertube.org/admin/remote-storage
    // on 2026-08-28, per the page's caption discipline.
    label: "Uploads and storage",
    cells: [
      "Uploads and transcodes work on local disk; with remote storage configured, files move to S3 after processing.",
      "Object-storage-native: upload chunks stream straight to the storage backend and never touch the server's local disk. A server dying mid-upload loses nothing.",
    ],
  },
  {
    // PeerTube cell checked against docs.joinpeertube.org/install/docker on
    // 2026-08-30. Their documented path, stated plainly and without
    // adjectives — an admin who has run it should recognise their own evening.
    label: "Operations",
    cells: [
      "The documented Docker path: three curl commands for the compose file, the env file and an nginx template; five placeholders hand-edited in .env; the first TLS certificate generated by hand with certbot, renewed by a container after that; and the initial root password read out of the container logs.",
      "One command in; vidra doctor runs 26 checks and names the failure; deploy, rollback, backup and restore are scripted.",
    ],
  },
  {
    // PeerTube cell checked against docs.joinpeertube.org/admin/remote-runners
    // on 2026-08-30. "Can take transcoding off the main server" understated it
    // by four job types.
    label: "Growing past one box",
    cells: [
      "Remote runners take five job types off the main server: VOD transcoding, studio transcoding, live transcoding, automatic transcription and storyboard generation.",
      `The same image splits into api and worker roles. Replicas hold leases and elect leaders — soak-tested at two replicas: ${SCALE.soak} deliveries with zero duplicates, and ${SCALE.soakControlDeliveries} deliveries with ${SCALE.soakControlDuplicates} duplicates once the safeguards were removed on purpose, so the harness is known to catch it. A CDN with purge is wired in. Multi-CDN steering, studio DRM and multi-region are the published roadmap, not the release.`,
    ],
  },
  {
    // joinpeertube.org/faq, checked 2026-08-30: hardware requirements are
    // published; no money figure appears anywhere on the page.
    label: "What it costs to run",
    cells: [
      "They publish hardware requirements — 1 vCore and 1.5 GB at minimum, 4 vCore and 4 GB for around a thousand concurrent viewers, 8 vCore and 8 GB with transcoding on the same machine. They publish no price.",
      "Two published profiles with prices — $56/mo (4 vCPU, 8 GB) and $168/mo (8 vCPU, 16 GB on dedicated cores) — and a calculator that shows its arithmetic, block storage and transfer allowance included.",
    ],
  },
  // The four rows below are PeerTube's, and they are in the table rather than
  // left to be inferred from their absence. A comparison with no losing rows
  // is an advertisement.
  {
    // joinpeertube.org/faq, checked 2026-08-30.
    label: "Native mobile apps",
    cells: [
      "Official iOS and Android apps from Framasoft, on the App Store, Google Play and F-Droid.",
      "None. The web app is installable as a PWA; there is no native client and none is on the roadmap.",
    ],
  },
  {
    // packages.joinpeertube.org's own index API, counted 2026-08-30.
    label: "Plugins and themes",
    cells: [
      "A plugin and theme system, with 180 plugins and 54 themes in PeerTube's own index as of 30 August 2026.",
      "No plugin system. What ships in the release is what the instance does.",
    ],
  },
  {
    // docs.joinpeertube.org/admin/following-instances, checked 2026-08-30.
    label: "Mirroring another instance",
    cells: [
      "Server redundancy: opt into caching videos from platforms you follow, and let them cache yours, by strategy in production.yaml.",
      "No equivalent. Public media carries its CIDs in the API so anyone can pin a copy on IPFS — a different mechanism, and not a promise that anyone will.",
    ],
  },
  {
    // vidra-search/internal/store/store.go:32 — `cfg.MaxConns = 10`, the only
    // occurrence in the file and no environment read anywhere near it. This is
    // vidra-search's constraint specifically. vidra-core's pool IS
    // configurable, via DB_MAX_CONNS, and must not be described this way.
    label: "Managed PostgreSQL",
    cells: [
      "Supported: point the instance at an external or managed PostgreSQL in production.yaml.",
      "Not supported at launch. Vidra's search service pins its pool at 10 connections with no environment override, so there is no way to size it against a managed plan's connection cap.",
    ],
  },
  {
    label: "Moving an instance",
    cells: [
      "Home ground — nothing to move.",
      "A one-way importer reads a PeerTube database and media store read-only and maps users, channels, videos, comments, playlists and follows. Nothing exports back.",
    ],
  },
  {
    label: "Licence",
    cells: [
      "AGPL v3.",
      "AGPL v3 — the same licence. No difference to invent here.",
    ],
  },
];

const MIGRATION_STEPS = [
  "Stand up the Vidra instance first, on the sizing your catalogue needs — the importer needs somewhere to land.",
  "Point the importer at your PeerTube database and media store. It reads the source read-only; the run is idempotent and resumable, and --dry-run shows the plan first.",
  "It maps users, channels, videos, thumbnails, chapters, comments, ratings, playlists and follows — original publication dates and view counts included.",
  "Cut over when it is done. The importer is one-way: nothing writes back to PeerTube, so your source instance stays untouched until you retire it.",
];

export default function ComparePeerTubePage() {
  return (
    <>
      {/* 1 — Hero. Ink. The clean-room admission leads: it is the page's
          credibility down-payment. */}
      <section className="on-ink bg-ink text-onink">
        <div className="measure-text py-12 md:py-24">
          <Eyebrow ground="ink">Compare</Eyebrow>
          <Head as="h1" className="mt-3">
            Vidra and PeerTube, compared.
          </Head>
          <Standfirst ground="ink" className="mt-5">
            Vidra is a clean-room implementation — not a fork, not
            PeerTube-API-compatible. Here is where the two differ, where
            PeerTube is ahead, and what moving an instance across involves.
          </Standfirst>
        </div>
      </section>

      {/* 2 — The short answer. Paper. Concessions come first. */}
      <Section ground="paper">
        <Eyebrow>The short answer</Eyebrow>
        <div className="text-body mt-5 flex max-w-[66ch] flex-col gap-4 text-onpaper-2">
          <p>
            PeerTube is the mature choice: years in production, a plugin
            system, a large ecosystem of instances, and in-player peer-to-peer
            that shares playback bandwidth between viewers. Vidra has none of
            those — it is at {VERSION}, it has no plugin system, and P2P is on
            the roadmap, not in the release.
          </p>
          <p>
            What Vidra offers instead is the operator&apos;s path: one command
            installs it, vidra doctor runs 26 checks and names the failure, and
            deploy, rollback, backup and restore are scripted, with published
            sizing that carries prices. It also speaks ATProto: viewers can
            sign in with Bluesky or any PDS, and public videos can cross-post
            to Bluesky — PeerTube federates over ActivityPub only. Vidra also
            ships direct messages — including an end-to-end encrypted mode
            with disappearing timers — where PeerTube has no user-to-user
            messaging at all.
          </p>
          <p>
            If you run PeerTube happily, keep running it. If operations are the
            pain, or your audience lives on Bluesky, Vidra was built for
            exactly that — and a one-way importer moves an existing instance
            across.
          </p>
        </div>

        {/* Containment, stated rather than implied. A comparison page that
            cannot name the reader it should turn away is a sales page, and
            the reader who installs the wrong one finds out over a weekend. */}
        <h2 className="text-sub mt-10">Use PeerTube if</h2>
        <ul className="text-body mt-4 flex max-w-[66ch] list-disc flex-col gap-3 pl-6 text-onpaper-2 marker:text-label">
          <li>
            <strong className="font-bold text-onpaper">
              Your audience is on phones.
            </strong>{" "}
            PeerTube has official iOS and Android apps. Vidra has a web app you
            can install as a PWA, and no native client.
          </li>
          <li>
            <strong className="font-bold text-onpaper">
              You depend on a plugin or a theme.
            </strong>{" "}
            PeerTube&apos;s index carries 180 plugins and 54 themes. Vidra has
            no plugin system, so anything it does not ship, it does not do.
          </li>
          <li>
            <strong className="font-bold text-onpaper">
              You want a production record.
            </strong>{" "}
            PeerTube is at 8.2.4 with years of public instances behind it.
            Vidra is at {VERSION}, and no instance outside the author&apos;s is
            known to be running it. That gap is real and no amount of test
            coverage substitutes for it.
          </li>
        </ul>
      </Section>

      {/* 3 — The table. Ink. Visible verification caption: the [verify]
          discipline, made legible. */}
      <Section ground="ink" media>
        <div className="max-w-[1080px]">
          <Eyebrow ground="ink">Side by side</Eyebrow>
          {/* Deliberately uncounted: a counted heading is the count-drift
              failure class waiting to recur every time a row is added. */}
          <Head className="mt-3">The differences that decide it.</Head>
        </div>
        <div className="mt-8">
          <Comparison
            columns={COLUMNS}
            rows={ROWS}
            emphasisIndex={1}
            srCaption="Vidra compared with PeerTube"
          />
        </div>
        <p className="text-small mt-6 max-w-[72ch] text-onink-2">
          PeerTube column checked on 30 August 2026 against PeerTube&apos;s own
          documentation, repository and package index, at v8.2.4 — released 4
          August 2026, and the current stable. 8.3.0-rc.1 has been tagged since
          25 August 2026; when it goes stable this column gets another pass.
        </p>
      </Section>

      {/* 4 — Migrating. Paper. */}
      <Section ground="paper">
        <Eyebrow>Migrating</Eyebrow>
        <Head className="mt-3">One way, read-only at the source.</Head>
        <ol className="text-body mt-5 flex max-w-[66ch] list-decimal flex-col gap-3 pl-6 text-onpaper-2 marker:text-label">
          {MIGRATION_STEPS.map((step) => (
            <li key={step.slice(0, 32)}>{step}</li>
          ))}
        </ol>
        <p className="mt-6">
          <TextLink href={DOCS.migration} external>
            Read the migration overview →
          </TextLink>
        </p>
      </Section>

      {/* 5 — Closing CTA. Ink. */}
      <Section ground="ink">
        <Head>One command to see for yourself.</Head>
        <div className="mt-6 flex flex-wrap gap-3">
          <Button href={INSTALL_ANCHOR} variant="vidra" size="large">
            Install Vidra
          </Button>
          <Button href={DOCS.migration} external variant="ice-outline" size="large">
            Read the migration overview
          </Button>
        </div>
      </Section>
    </>
  );
}
